### ISSUE TITLE
[wwawing.com] WWA Wing を開発したい人へのナビゲーション追加

### ISSUE THREAD

**Issue by aokashi** [WWAWing/sites#12]
## 目的
wwawing.com では、WWA Wing にコントリビュート出来ると記載が含まれている。

ただし、これから WWA Wing を扱ってみたい、開発したい人にとっては、情報量が不足していて、開発の機会を失っている可能性がある。

開発した人にとっての有力な情報を加えるようにして、WWA Wing のコントリビュートの活性化を狙いたい。

## 想定される内容
様々な方法があるが、下記の方法が考えられる。

- wwawing.com の "開発にご協力を！" に "興味がありましたら、 Discord コミュニティに是非ご参加ください" といった文を含む。
- [WWA Wing のドキュメント](https://github.com/WWAWing/docs.wwawing.com)を整備する。
- WWA Wing の変更内容やトピックスをまとめたブログを新設する。

## 注意事項
- TypeScript や npm などをある程度学習している方の参加を推奨するような表記を含めると良い。
- 貢献は一口と言っても2つに分かれるため、この2通りを示すような表記をすると良い。
  - 技術貢献 → GitHub か、 Slack
  - 要望 → WWA コミュニティ (Discord)

**Comment by enloyable** [comment]
私自身が感じたことなのですが、扱ってみたい！と、開発したい！は割と要求レベルが段違いです。
　面倒いのでまるっと端折りますが、開発関連だと私自身もsave.jsいじりに難儀しており、しかも私自身関連のことが、issueを増やしてしまってる状態です…（割と私自身もそのことに悩んでます）

**Comment by enloyable** [comment]
（私自身のissueが負担とメリット両方強いことが多いからわりとアレ…）

**Comment by enloyable** [comment]
開発の機会を増やすことは、そちらの負担を増やしてしまうことでもあるんですよ…。色々と自分自身でも解ってるからかなり言いにくいことではあるけど、たまには休んでください…

**Comment by aokashi** [comment]
> 私自身が感じたことなのですが、扱ってみたい！と、開発したい！は割と要求レベルが段違いです。

実際そうです。
この Issue のターゲットとしては、 TypeScript や node などの知識をある程度学習した方が対象になります。
(説明不足でした。)

> 開発の機会を増やすことは、そちらの負担を増やしてしまうことでもあるんですよ…。色々と自分自身でも解ってるからかなり言いにくいことではあるけど、たまには休んでください…

WWA Wing の開発については任意ですので、取り組みたい方が取り組みたいタイミングで行えればそれで良いのかなと思います。
WWA Wing Team 外のメンバーについては、多少の連絡は入りますが、 "じゃあそれやって！" みたいな連絡はありません。

**Comment by enloyable** [comment]
つまり、割と本格的な開発の知識のある方向けですね。

**Comment by enloyable** [comment]
ソースがある程度読める私でさえレベルがおそらく足りませんし、そうすると本当にwwaのdiscord内ではwwawingteamだけかな、と思います。wwaのdiscordは遊びたい方が多いですし。

**Comment by enloyable** [comment]
同様の理由から、技術者募集という文言にしたほうがいいと思いますよ。

**Comment by matsuyuki-a** [comment]
OSSへの貢献というのは、単に技術的なことだけじゃなくて、もっとこうした方がいいとかいうような要望を出す、というのも（WWA開発においては）大事なのかなぁと思います。

ただ、GitHubで実際にコードをどうこう、となってくると要求スキルが変わってくるのかなぁというのも事実ですね。

どちらの種類の貢献も大事だとは思うのですが、それぞれ要求スキルが違うのもまた事実だと思うので、2つに分けて併記するのも悪くないかもしれないですねー

**Comment by matsuyuki-a** [comment]
前者は、Discordへ、後者はGitHub(+Slack?)へ誘導できる動線があるのが望ましいのかもしれないですね

**Comment by enloyable** [comment]
その代わりに、技術者向けのかなり専門的な情報や、技術に関することはしっかりと載せる。上級者の方をターゲットにする以上、当然上級者向けの情報はしっかりとすべきでしょう。

**Comment by enloyable** [comment]
私がその中間であるからこそ、言える意見かもしれませんね。

**Comment by enloyable** [comment]
まつゆきさんの提案に賛成いたします。discordはwwaを遊びたい！って人を大切にしましょ。

**Comment by matsuyuki-a** [comment]
WWAWing ブログが整備されたことや、プレイしたい人の情報はFanSquareに分けるというポリシーが徹底されたこともあり、一旦このIssueはクローズします。

ブログやドキュメントへの導線がいまいちというのは、別のIssueで議論したいと思います。
