### ISSUE TITLE
[wwawing.com] WWA Phoenix の説明をもうちょっと親切にする

### ISSUE THREAD

**Issue by aokashi** [WWAWing/sites#15]
## 目的
- https://github.com/WWAWing/WWAWing/issues/131 を参照

## 考えていること
- WWA Phoenix のページとは別に、使用方法のHTMLファイルを別途作成し、その中に PC と スマートフォン でそれぞれ作成する。
- スクリーンショットは添えたい。

**Comment by matsuyuki-a** [comment]
WWA Phoenix については、WWA Phoenix の方のページで Issue管理しようと思うので close します
