### ISSUE TITLE
WWA Wing ブログの検討

### ISSUE THREAD

**Issue by aokashi** [WWAWing/sites#166]
WWA Wing のアップデート情報を発信する WWA Wing 開発ブログの導入を考えています。

## 目的
- 更新情報の分散化解消
    - これまで自分のブログで更新情報を掲載しているが、掲載場所が離れているのでわかりにくい
- WWA Wing 本サイトとの統合準備

## 現時点で分かっていること
- 静的サイトジェネレーターでブログを作る
- 記事は Markdown 形式で記述する
- WWAWing Team に所属しているメンバーが自由に執筆できる

## 考えてはいるけど議論が必要なこと
- 開発ブログを本リポジトリの中に入れる

## まだ分からないこと
- 画像といったリソースの配置場所
- サイトのデザインを WWA Wing 公式サイトと一体化するか？
- HUGO のような単純な方式の静的サイトジェネレーターで開発するか？ Gatsby のようなビューフレームワークを活用した静的サイトジェネレーターで開発するか？
  - #108 の件もあるので慎重に決めたい

**Comment by matsuyuki-a** [comment]
現行の https://aokashi.hatenablog.jp/ みたいに外部ホストでもよいかも

**Comment by aokashi** [comment]
はてなブログとかの外部サービスの活用かー
はてなブログだと複数人での運営は、ブログの運営者のみ PRO 課金が必要になるので、そこのところどうなのとは思っている

**Comment by matsuyuki-a** [comment]
> 画像といったリソースの配置場所
どんなジェネレータを使うか次第かな

> サイトのデザインを WWA Wing 公式サイトと一体化するか？
#108 をやるなら一体化したい！

> HUGO のような単純な方式の静的サイトジェネレーターで開発するか？ Gatsby のようなビューフレームワークを活用した静的サイトジェネレーターで開発するか？
#108 をやるなら Gatsbyかな デザインを統一しないなら外部ホストでもよいのかも

**Comment by matsuyuki-a** [comment]
あるいは、誰でも書き込める、を我慢して、誰か運営者に投稿を委託するとか

**Comment by aokashi** [comment]
手間を考えると楽なのでできれば複数人の運営にしたい 😇 

1. Gatsby を本リポジトリ内に設置
  - WWA Wing メインサイトと統合出来る
  - 構築コストが掛かる
2. 外部サービスを活用する
  - 構築コストが秒で済む
  - デザインは WWA Wing メインサイトとは別になる
  - サービスによっては有料
3. 仮ブログを本リポジトリ内に設置して、後にリニューアル
  - `1.` と `2.` のあわせ技
  - 仮ブログの際は HUGO か 11ty を使用し、リニューアルの際は Gatsby に差し替える
  - 仮ブログの構築コストはあまりかからない (と信じたい)
  - 仮ブログの設置からリニューアルまで全体的に見て手間は掛かる傾向にある

**Comment by aokashi** [comment]
まずは Gatsby で用意されている適当な gatsby-starter を利用してブログを構築し、後で手直しする形が良いかな

**Comment by matsuyuki-a** [comment]
よさそう

**Comment by aokashi** [comment]
方針を変更し、 WWA Wing 開発ブログを WWA Wing ブログに変更します。

WWA Wing ブログでは、 WWA Wing のアップデート情報のほかにも、 WWA Wing の使用方法といった WWA の使用やプレイに関するノウハウなどをまとめて掲載するつもりでいます。

**Comment by aokashi** [comment]
導入済みなので Close します。
