### ISSUE TITLE
WWA コミュニティの参加のご案内を削除するか、別の場所に移転する

### ISSUE THREAD

**Issue by aokashi** [WWAWing/sites#270]
[このリポジトリの Wiki](https://github.com/WWAWing/sites/wiki) に WWA Discord コミュニティの参加のご案内や使用方法などがありますが、これを削除するか、別の場所に移行する予定です。

## 想定される案
- すでに WWA コミュニティに参加しようとしているユーザーは Discord は知っているだろうし、使用方法はサーバーの「はじめに」チャンネルに書いてあるので、案内は削除してしまおう
- 案内のページは WWA FanSquare のページに移行しよう
  - 現在、 WWA FanSquare は大人の事情で既存のサイトへのページ追加にコストがかかる見込みから、悩んでいるところがある
- とりあえず、ページを別リポジトリの Wiki に移行しよう
  - 一番手っ取り早いが、 WWA コミュニティに参加しようとしているユーザーは GitHub の Wiki に慣れているかわからない可能性がある

**Comment by matsuyuki-a** [comment]
Fandom のWWA Wikiとかに移すのはいかがでしょうか？

**Comment by matsuyuki-a** [comment]
移転終わってそうなのでcloseします。
このリポジトリのWikiにあるリンクも役目を終えてそうなので消そうと思います
