### ISSUE TITLE
get.wwawing.com を廃止し、wwawing.com/downloads に移転する...?

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/sites#48]
現在、1つのリポジトリに対して2つのnetlifyのサイトが動く構成になっている。
複数のサイトがあること自体は問題ではないが、同じrootディレクトリを共有しているので、これを解消したい。（解消しないと 同じ netlify.toml を参照してしまうなどの問題がある。)
get.wwawing.com からはリダイレクト対応を行う。

**Comment by matsuyuki-a** [comment]
get.wwawing.com と wwawing.com のスクリプトを分離できればそれでも可

**Comment by aokashi** [comment]
- get.wwawing.com を wwawing.com に統合してリポジトリの monorepo をやめる
- get.wwawing.com は downloads (仮称) に移転
- 本 Issue が終わり次第開発ブログの設立作業に着手する (#166 #167)
    - なるべくはやめに
